#! /usr/bin/env python3

import pdb
import sys
import logging
import argparse

parser = argparse.ArgumentParser(description=sys.argv[0])
parser.add_argument('-d', '--debug', action='store_true', help='Start Python interactive debugger')
parser.add_argument('-v', '--verbose', action='count', help='Enable debugging')
args = parser.parse_args()

if args.debug:
  pdb.set_trace()

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg)s')
log = logging.getLogger()
log.setLevel(logging.WARNING - (args.verbose or 0)*10)
