#! /usr/bin/env python

class C1(object):
  pass

class C2(C1):
  pass

def see(expr):
  value = eval(expr)
  print '{expr}: {value!r}'.format(**locals())

see('issubclass(C1, object)')
see('issubclass(C2, object)')
see('issubclass(C2, str)')
