#! /usr/bin/env python

# this will import from lib/custom_class.py
from custom_class import CustomClass

custom_instance = CustomClass('this is a test')
print(f'custom_instance.data: {custom_instance.data}')
