#! /usr/bin/env python

# conditional loop

obj = {
  1: 'one',
  2: 'two',
  3: 'three',
  4: 'four',
  5: 'five',
  6: 'six',
  7: 'seven',
  8: 'eight',
  9: 'nine',
  10: 'ten',
}

for (key, value) in {key: value for (key, value) in obj.items() if (key%2)}:
  print '{key!r}={value!r}'.format(**locals())
