#! /usr/bin/env python3

import sys
import csv
import signal
import logging
import argparse

parser = argparse.ArgumentParser(description='simple csv reader')
parser.add_argument('-v', '--verbose', action='count', help='Enable debugging')
args = parser.parse_args()

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg)s')
log = logging.getLogger()
log.setLevel(logging.WARNING - (args.verbose or 0)*10)

signal.signal(signal.SIGPIPE, lambda signum, stack_frame: exit(0))

if sys.stdin.isatty():
  parser.error('stdin must be redirected')

reader = csv.reader(sys.stdin)
for row in reader:
  print(row)
