#! /usr/bin/python

import pdb
import datetime

epoch = datetime.datetime.utcfromtimestamp(0)
now = datetime.datetime.now()

format = "%Y-%m-%d %H:%M:%S"
saturday = datetime.datetime.strptime("2017-11-04 12:00:00", format)
sunday = datetime.datetime.strptime("2017-11-05 12:00:00", format)

print "%s - %s = %s" % (sunday, saturday, sunday-saturday)
