#! /usr/bin/env python

"""
   Trying out technique to set an option via an environment variable
"""

import os
import re

def show(expr):
  value = eval(expr)
  print '{expr}: {value!r}'.format(**locals())

verbose = os.environ.get('VERBOSE')
verbose = re.match('((y(es?)?)|(t(r(ue?)?)?)|1)$', verbose if verbose else '', re.IGNORECASE) != None
show('verbose')
