#! /usr/bin/env python2

import os

def addPipe(num):
  global pipes
  for iteration in range(num):
    pipes.append(os.pipe())
  print 'Pipes:{pipes} Fds:{fds}'.format(
    pipes=len(pipes),
    fds=len(os.listdir('/dev/fd')),
  )
  
pipes = []

addPipe(0)
addPipe(10)
addPipe(100)
addPipe(250)
