#! /usr/bin/env python3

import os

filename = os.path.join(os.environ['HOME'], '.profile')
with open(filename) as stream:
  data = stream.read()

print(f'{data!r}')

lines = data.splitlines()
print(f'{lines}')

lines = data.strip().split('\n')
print(f'{lines}')
