#! /usr/bin/env python

import os

class File(object):
  def __init__(self, path):
    self.path = path
    self.exists = os.path.exists(path)
    self.mode = os.stat(path).st_mode if self.exists else None

path = '/'
print(f'{oct(File(path).mode)}')
