#! /usr/bin/env python

"""
   A test to see if we can take an arbitrary string and replace any passwords that appear in it:

     $ echo '{"passwd": "xyz" } PASSWORD=123' | ./hidepassword
     '{"passwd": "xyz" } PASSWORD=123': {"passwd": "********" } PASSWORD=********
"""

import re
import sys

regexp = re.compile('\S*PASSW(?:OR)?D\S*\W+([-a-zA-Z0-9!@#$%^&*()_+=[\]()\\|;:,./<>?]+)(:?\W|$)', re.IGNORECASE)
while True:
  if sys.stdin.isatty():
    sys.stdout.write('> ')
  line = sys.stdin.readline()
  if not line:
    break

  line = line.strip('\n')

  if not sys.stdin.isatty():
    sys.stdout.write('{line!r}: '.format(**locals()))

  hits = list(regexp.finditer(line))
  if hits:
    for hit in hits[-1::-1]:
      line = line[:hit.start(1)] + ('*'*8) + line[hit.end(1):]
    print line
  elif not sys.stdin.isatty():
    print 'None'
