#! /usr/bin/env python2

import logging
import argparse

class Handler(logging.StreamHandler):
  def emit(self, record):
    msg = self.format(record)
    self.stream.write(msg.upper())

parser = argparse.ArgumentParser()
parser.add_argument('-v', '--verbose', dest='verbose', action='count', help='Enable debugging')
args = parser.parse_args()

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg)s')
log = logging.getLogger()
log.addHandler(Handler())
log.setLevel(logging.DEBUG if args.verbose else logging.INFO)

log.info('This is a test')
