#! /usr/bin/env python2

import logging

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg)s', filename='logswitch.log')
log = logging.getLogger()
log.setLevel(logging.DEBUG)

# log.info('before switch')
# logging.basicConfig(filename='logswitch.log')
# log = logging.getLogger()
log.info('after switch')
