#! /usr/bin/env python

class Obj(object):
  def __init__(self, value):
    self.value = value

def see(expr):
  value = expr.format(**globals())
  print '{expr}: {value}'.format(**locals())

objs = [Obj('foo')]
for pos in range(10):
  objs.append(Obj(objs[-1]))
obj = objs[-1]

fmt = '{{obj{attrs}}}'.format(attrs='.value' * (len(objs)))
print fmt.format(**locals())

see('{objs[0]}')
see('{objs[int(-1)]}')
