#! /usr/bin/env python

import logging
import string

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg).256s')
log = logging.getLogger()
log.setLevel(logging.DEBUG)

log.debug(string.letters * 100)
