#! /usr/bin/env python2

def doit(limit):
  global iteration

  iteration += 1
  print 'Loop {iteration}'.format(**globals())
  for datum in range(limit):
    print iteration, datum
  else:
    print 'Loop {iteration} else'.format(**globals())

iteration = 0
doit(10)
doit(0)
