#! /usr/bin/env python2

import sys
import pdb

def methodFoo():
  print 'Welcome to foo!'

def methodBar():
  print 'Welcome to bar!'

pdb.set_trace()

assert len(sys.argv) > 1

methods = sys.modules[__name__]

for name in sys.argv[1:]:
  methodName = 'method' + (name.capitalize())
  if hasattr(methods, methodName):
    method = getattr(methods, methodName)
    method()
  else:
    sys.stderr.write('{methodName!r} is invalid\n'.format(**locals()))
