#! /usr/bin/env python

import os
import time
import datetime
from multiprocessing import Process, Manager

def say(msg):
  print '{now} {msg}'.format(now=datetime.datetime.now(), msg=msg)

def fun(x):
  say('Welcome to fun() were my pid is {pid} and ppid is {ppid}'.format(pid=os.getpid(), ppid=os.getppid()))
  time.sleep(5)
  x += range(5)
  say('Goodbye from fun()')

say('Welcome to main script were my pid is {pid}'.format(pid=os.getpid()))
manager = Manager()
x = manager.list()
p = Process(target=fun, args=(x,))
p.start()
p.join()
say('Goodbye from main script, x={x}'.format(**locals()))

