#! /usr/bin/python

import sys
import pdb
import datetime

epoch = datetime.datetime.utcfromtimestamp(0)
local = datetime.datetime.fromtimestamp(0)

if len(sys.argv) > 1:
  format = "%Y-%m-%d %H:%M:%S"
  try:
    secs = (datetime.datetime.strptime(sys.argv[1], format)-local).total_seconds()
  except Exception as e:
    sys.stderr.write("Caught %s parsing %s with %s\n" % (repr(e), repr(sys.argv[1]), repr(format)))
    exit(1)
else:
  secs = (datetime.datetime.now()-local).total_seconds()

epoch = datetime.datetime.utcfromtimestamp(secs)
local = datetime.datetime.fromtimestamp(secs)

diff = local-epoch
if diff.total_seconds() == 0:
  print "Local time %s is the same as UTC" % local
elif diff.total_seconds() > 0:
  print "Local time %s is %s east of UTC" % (local, diff)
else:
  diff = epoch-local
  print "Local time %s is %s west of UTC" % (local, diff)

# pdb.set_trace()
