#! /usr/bin/env python2

import sys
import argparse

def see(expr):
  value = eval(expr)
  sys.stderr.write('{expr}: {value!r}\n'.format(**locals()))

parser = argparse.ArgumentParser()
parser.add_argument('--bar', dest='bar', nargs='?')
parser.add_argument('foo', nargs='?')
args = parser.parse_args()

see('vars(args)')
see('args.bar')
see('args.foo')

print 'Done'
