#! /usr/bin/env python2

import sys
from optparse import OptionParser

parser = OptionParser('Syntax: {pgm} --blah BLAH'.format(pgm=sys.argv[0]))
parser.add_option('-b', '--blah', dest='blah', help='blah blah blah', required=True)
(opts, args) = parser.parse_args()
print 'opts: {opts}'.format(**locals())
print 'args: {args}'.format(**locals())
