#! /usr/bin/env python2

def fun(x):
  print('x={x!r}'.format(**locals()))
  return repr(x)

ret = map(fun, ['str', u'unicode', 42, 3.14152654, True])
print(ret)
# print('map() returned a {}'.format(type(ret)))
# for datum in ret:
#   print('datum is a {}'.format(type(datum)))
