#! /usr/bin/env python3

import sys
import subprocess

print(f'{sys.argv}')
assert len(sys.argv) > 1

p = subprocess.Popen(sys.argv[1:], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
(stdout, stderr) = p.communicate()
rc = p.wait()
print(f'{rc}, {stdout!r}, {stderr!r}')

stdout1 = str(stdout)
stderr1 = str(stderr)
print(f'{rc}, {stdout1!r}, {stderr1!r}')

stdout2 = stdout.decode('utf-8')
stderr2 = stderr.decode('utf-8')
print(f'{rc}, {stdout2!r}, {stderr2!r}')
