#! /usr/bin/env python

import os
import sys
import paramiko

assert len(sys.argv) > 1

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(hostname=os.environ['STAGING'], username='ubuntu')
channel = client.get_transport().open_session()
channel.exec_command(' '.join(sys.argv[1:]))
print 'Exit status: {status}'.format(status=channel.recv_exit_status())
client.close()
