#! /usr/bin/env python

import os
import paramiko

client = paramiko.SSHClient()
client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
client.connect(hostname=os.environ['STAGING'], username='ubuntu')
(stdin, stdout, stderr) = client.exec_command('TZ=EST5EDT date')
stdin.close()
print '{stdout!r}, {stderr!r}'.format(stdout=stdout.read(), stderr=stderr.read())
client.close()
