#! /usr/bin/env python

import sys
import time
import threading
import subprocess

class Echo(threading.Thread):
  def __init__(self, in_stream, out_stream):
    super(Echo, self).__init__()
    self.in_stream = in_stream
    self.out_stream = out_stream
    self.start()

  def run(self):
    while True:
      line = self.in_stream.readline()
      if line:
        self.out_stream.write(line)
      else:
        break
  
assert len(sys.argv) > 1, 'Syntax: {pgm} CMD ...'.format(pgm=sys.argv[0])

threads = []
p = subprocess.Popen(sys.argv[1:], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
threads.append(Echo(p.stdout, sys.stdout))
threads.append(Echo(p.stderr, sys.stderr))
rc = p.wait()
while threading.active_count() > 1:
  time.sleep(1)
exit(rc)
