#! /usr/bin/env python2

import sys
import time
import string
import random
import logging
import argparse
import datetime

parser = argparse.ArgumentParser(description='phony output')
parser.add_argument('-v', '--verbose', dest='verbose', action='store_true', help='Enable debugging')
args = parser.parse_args()

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg)s')
log = logging.getLogger()
log.setLevel(logging.DEBUG if args.verbose else logging.WARNING)

start = datetime.datetime.now()
while (datetime.datetime.now() - start) < datetime.timedelta(minutes=1):
  time.sleep(random.randint(0, 10000)/1000.0)
  for loop in range(random.randint(0, 80)):
    sys.stdout.write(random.choice(string.printable))
  print ''
