#! /usr/bin/env python2

import sys
import json
import pprint

def banner(s):
  border = '*' * (len(s) + 4)
  print border
  print '* {s} *'.format(**locals())
  print border

stuff = ['spam', 'eggs', 'lumberjack', 'knights', 'ni']
stuff.insert(0, stuff[:])
pp = pprint.PrettyPrinter(indent=4)

banner('pprint')
pp.pprint(stuff)
print ''
banner('json')
json.dump(stuff, sys.stdout, indent=2, sort_keys=True)
