#! /usr/bin/env python

import os
import subprocess

p = subprocess.Popen(['bash'], stdin=subprocess.PIPE)
p.stdin.write('''
loop=0
while [ $loop -lt 1000000 ]
do
  let 'loop=loop+1'
  echo $loop
done
''')
p.stdin.close()
p.wait()

times = os.times()
print times
