#! /usr/bin/env python2

import socket
import logging
import argparse

parser = argparse.ArgumentParser(description='Query host through socket module')
parser.add_argument('hosts', metavar='host', nargs='+', help='One or more hosts to query')
parser.add_argument('-v', '--verbose', dest='verbose', action='store_true', help='Enable debugging')
args = parser.parse_args()

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg)s')
log = logging.getLogger()
log.setLevel(logging.DEBUG if args.verbose else logging.INFO)

for host in args.hosts:
  ret = socket.gethostbyname_ex(host)
  log.info('{host}: {ret}'.format(**locals()))
