#! /usr/bin/env python

import random
import string

def randomName():
  return ''.join([random.choice(string.lowercase) for iteration in range(random.randint(1,10))])

x = {}
for iteration in range(10):
  x[randomName()] = random.randint(1, 100)

print x
print sorted(x.items(), key=lambda item: item[1])
