#! /usr/bin/env python

import random
import logging
import argparse

parser = argparse.ArgumentParser(description='Generate a number of integers between low and high numbers', formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('-L', '--low', dest='low', help='Lowest number', type=int, default=0)
parser.add_argument('-H', '--high', dest='high', help='Highest number', type=int, default=99)
parser.add_argument('-C', '--count', dest='count', help='Number of numbers', type=int, default=1000)
parser.add_argument('-v', '--verbose', dest='verbose', action='store_true', help='Enable debugging')
args = parser.parse_args()

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg)s')
log = logging.getLogger()
log.setLevel(logging.DEBUG if args.verbose else logging.WARNING)

for iteration in range(args.count):
  print(random.randint(args.low, args.high))
