#! /usr/bin/env python3

"""
Explore `TypeError: cannot use a string pattern on a bytes-like object` exception with re.search() using the stdout "string" of subprocess.Popen()
"""

import re
import subprocess

regexp = re.compile(r'(\d{4})')

p = subprocess.Popen(['date'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
(stdout, stderr) = p.communicate()
rc = p.wait()

try:
  match = regexp.search(stdout)
except Exception as e:
  print(f'Caught: `{e!s}`')
else:
  print(match.groups() if match else None)

for line in str(stdout).splitlines():
  try:
    match = regexp.search(line)
  except Exception as e:
    print(f'Caught: `{e!s}`')
  else:
    print(match.groups() if match else None)
