#! /usr/bin/env python2

import re
import argparse

parser = argparse.ArgumentParser()
# parser.add_argument('pattern', help='A regular expression pattern')
parser.add_argument('replacement', help='Replacement string')
parser.add_argument('haystack', metavar='string', help='Original string to search')
args = parser.parse_args()

pattern = 'PASSW(?:OR)?D[\'"]?[ :\t=]*(?:(?:u?[\'"])?)([-a-zA-Z0-9!@#$%^&*()_+=[\]\\|;:,./<>?]+)'

match = re.search(pattern, args.haystack, flags=re.IGNORECASE)
print match.groups() if match else None

print re.sub(pattern, args.replacement, args.haystack, flags=re.IGNORECASE)
