#! /usr/bin/env python

import logging

def safe_dict_get(root, *path):
  log.debug('root={root}, path={path}'.format(**locals()))
  if len(path) == 1:
    return root.get(path[0])
  else:
    return safe_dict_get(root.get(path[0], {}), *path[1:])

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg)s')
log = logging.getLogger()
log.setLevel(logging.DEBUG)

cfg = {
  'em': {
    'login': {
      'user': 'foo',
      'password': 'bar',
    }
  },
}

log.info(safe_dict_get(cfg, 'em', 'login', 'user'))
log.info(safe_dict_get(cfg, 'x', 'login', 'user'))
