#! /usr/bin/env python2

import pdb
import traceback

def stillmorefun():
  morefun()

def morefun():
  fun()

def fun():
  traceback.print_stack()
  tb = traceback.extract_stack()
  print type(tb)
  print len(tb)
  print tb
  # print '\n'.join([str(line) for line in tb])
  for line in tb:
    print type(line)
    # pdb.set_trace()
    print dir(line)
    print str(line)

for iteration in range(1):
  (lambda x: fun())(None)

morefun()
stillmorefun()
