#! /usr/bin/env python

import sys
import re

assert not sys.stdin.isatty(), 'stdin must be redirected'

regexp = re.compile('\s$')
nots = []

for arg in sys.argv[1:]:
  nots.append(re.compile(arg))

for line in sys.stdin.read().splitlines():
  if regexp.search(line) and (not any([curr.search(line) for curr in nots])):
    line += '$'
  print line
