#! /usr/bin/env python2

import sys
import logging
import argparse

parser = argparse.ArgumentParser(description='Test stdin')
parser.add_argument('-v', '--verbose', action='store_true', help='Enable debugging')
args = parser.parse_args()

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg)s')
log = logging.getLogger()
log.setLevel(logging.DEBUG if args.verbose else logging.WARNING)

if sys.stdin.isatty():
  print 'stdin is not redirected'
else:
  for line in sys.stdin.read().splitlines():
    print 'stdin: {line!r}'.format(**locals())
