#! /usr/bin/env python3

import logging
import argparse

from table import Table

parser = argparse.ArgumentParser(description='investigate table bug')
parser.add_argument('--boom', action='store_true', help='Cause exception')
parser.add_argument('-v', '--verbose', action='count', help='Enable debugging')
args = parser.parse_args()

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg)s')
log = logging.getLogger()
# log.setLevel(logging.DEBUG if args.verbose else logging.WARNING)
log.setLevel(logging.WARNING - (args.verbose or 0)*10)

table = Table('col1', 'col2')
table.add('row1, col1', 'row1, col2')
if args.boom:
  table.add('row2, col1')
print(str(table))
