#! /usr/bin/env python2

import os
import time

def display(label):
  print '{label}: {value!r}'.format(label=label, value=eval(label))

print 'TZ={TZ}'.format(TZ=os.environ.get('TZ'))
# time.tzset()
display('time.tzname')
display('time.timezone/60.0/60.0')
