#! /usr/bin/env python

import sys
import signal
import logging
import argparse

parser = argparse.ArgumentParser(description=sys.argv[0])
parser.add_argument('-e', '--exception', action='store_true', help='Cause exception')
parser.add_argument('-v', '--verbose', action='count', help='Enable debugging')
args = parser.parse_args()

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg)s')
log = logging.getLogger()
log.setLevel(logging.WARNING - (args.verbose or 0)*10)

print('Before `try` block')
try:
  if args.exception:
    open('/foobar')
finally:
  print('Inside `finally` clause')
print('Outside `finally` clause')
