#! /usr/bin/env python

import sys

import pytest
from pytest import assume

x = {'a': 1}

try:
  assert x['b'] == 2
except Exception as e:
  print('Caught: {!s}'.format(e))

if sys.version_info.major >= 3:
  try:
    with assume: assert x['c'] == 3
  except KeyError:
    print('Caught: {!s}'.format(e))
else:
  print('`with assume` not supported in Python 2')
