#! /usr/bin/env python

def fun(a, b, *values):
  print 'a: {a}'.format(**locals())
  print 'b: {b}'.format(**locals())
  print 'values: {values}'.format(**locals())
  print 'len(values): {size}'.format(size=len(values))

fun(1, 2, 3, 4, 5)
