#! /usr/bin/env python2

import sys
import argparse

def create_severities(*severities):
  """
     Create global severity tuples such as:
       INFO = (0, 'INFO')
       WARNING = (1, 'WARNING')
       .
       .
       .
  """
  least_severe = None
  most_severe = None

  for (pos, severity) in enumerate(severities):
    globals()[severity] = (pos, severity)
    if not least_severe:
      last_severe = globals()[severity]
      globals()['LEAST_SEVERE'] = last_severe
    most_severe = globals()[severity]

  globals()['MOST_SEVERE'] = most_severe

create_severities('DEBUG', 'INFO', 'WARNING', 'ERROR', 'FATAL')

def see(expr):
  value = eval(expr)
  sys.stderr.write('{value}: {expr!r}'.format(**locals()))

def debug(level, msg):
  result=(MOST_SEVERE[0] - (level[0] or 0)) <= 0
  severity = level[1]
  print '{msg}: {severity} {result}'.format(**locals())

parser = argparse.ArgumentParser()
parser.add_argument('-v', '--verbose', dest='verbose', action='count', help='Enable debugging - multiple uses increases debugging')
args = parser.parse_args()

debug(INFO, 'INFO')
debug(WARNING, 'WARNING')
debug(ERROR, 'ERROR')
debug(FATAL, 'FATAL')
