#! /usr/bin/env python2

import os
import sys
import stat

def see(expr):
  value = eval(expr)
  print '{expr}: {value!r}'.format(**locals())

see('sys.stdin.isatty()')

s = os.fstat(sys.stdin.fileno())
print str(s)
print 'mode: {s.st_mode:o}'.format(**locals())
see('stat.S_ISDIR(s.st_mode)')
see('stat.S_ISCHR(s.st_mode)')
see('stat.S_ISBLK(s.st_mode)')
see('stat.S_ISREG(s.st_mode)')
see('stat.S_ISFIFO(s.st_mode)')
see('stat.S_ISLNK(s.st_mode)')
see('stat.S_ISSOCK(s.st_mode)')
