#! /usr/bin/env python2

class MyObj(object):
  def __init__(self, *args, **kwds):
    assert not args, 'No positional arguments are supported'
       
    for key, value in kwds.items():
      setattr(self, key, value)
      self.enters = 0

  def __enter__(self):
    print '__enter_() drove: vars:{vars}'.format(vars=vars(self))
    self.enters += 1
    return self

  def __exit__(self, type, value, traceback):
    print '__exit__() drove: type={type}, value={value}, traceback={traceback}, vars:{vars}'.format(vars=vars(self), **locals())

with MyObj(x=42) as obj:
  print obj.x
