#! /usr/bin/env python

import re
import os
import sys
import json
import subprocess

def get_executable(default, *paths):
  for path in paths:
    if os.path.isfile(path):
      return path
  return default 

def try_numeric(s):
  try:
    return int(s)
  except:
    try:
      return float(s)
    except:
      return s

regexp = re.compile(r'\s*\|\s*')



p = subprocess.Popen([get_executable('osqueryi', 'c:/Program Files/osquery/osqueryi.exe')], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
p.stdin.write('select * from processes;'.encode())
# p.stdin.close()
(binary_stdout, binary_stderr) = p.communicate()
rc = p.wait()
assert rc == 0

headings = list()
processes = list()

for line in binary_stdout.decode().splitlines():
  tokens = regexp.split(line)
  if len(tokens) > 1:
    if len(headings) == 0:
      headings = tokens[1:-1]
    else:
      processes.append({key: try_numeric(tokens[pos+1]) for (pos, key) in enumerate(headings)})

json.dump(processes, sys.stdout)
