#! /usr/bin/env python3

import os
import sys
import signal
import logging
import argparse

parser = argparse.ArgumentParser(description=sys.argv[0])
parser.add_argument('-v', '--verbose', action='count', help='Enable debugging')
args = parser.parse_args()

logging.basicConfig(format='%(asctime)s %(levelname)s %(pathname)s:%(lineno)d %(msg)s')
log = logging.getLogger()
# log.setLevel(logging.DEBUG if args.verbose else logging.WARNING)
log.setLevel(logging.WARNING - (args.verbose or 0)*10)

signal.signal(signal.SIGPIPE, lambda signum, stack_frame: exit(0))

if sys.stdout.isatty():
  parser.error('You must redirect stdout')

stream = os.fdopen(sys.stdout.fileno(), 'w' if sys.version_info.major == 2 else 'wb')

for c in range(256):
  stream.write(chr(c) if sys.version_info.major == 2 else bytes([c]))
